#!/bin/bash
# scripts/port-forward-all.sh
# ⚠️  AUTO-GENERATED by Ansible from files/scripts/port-forward-all.sh.j2
# ⚠️  Do not edit this file directly — update the template or all.yml instead.
#
# Starts kubectl port-forward for all thesis MLOps UIs in the background.
# Services with type='ssh-only' (e.g. Jupyter) are already listening on
# VM localhost; they are listed for VSCode auto-detection but no
# kubectl is invoked for them.

export KUBECONFIG=/etc/rancher/k3s/k3s.yaml

# Build dynamic regex from configured ports for status/stop logic
ALL_PORTS_REGEX="9001|9000|8080|5000|3000|9090|9093|8000|8889"

forward_kubectl() {
  local local_port=$1 ns=$2 svc=$3 remote_port=$4 label=$5

  if ! kubectl get svc -n "$ns" "$svc" >/dev/null 2>&1; then
    echo "  SKIP  $label — svc/$svc not found in $ns (not yet deployed)"
    return
  fi

  if ss -tln 2>/dev/null | grep -q ":${local_port} "; then
    local pid=$(ss -tlnp 2>/dev/null | grep ":${local_port} " | grep -oP 'pid=\K[0-9]+' | head -1)
    if [ -n "$pid" ] && ps -p "$pid" -o cmd= 2>/dev/null | grep -q "kubectl"; then
      echo "  OK    $label — http://localhost:${local_port} (already running, PID $pid)"
    else
      echo "  BUSY  $label — port ${local_port} in use by non-kubectl process. Run: $0 stop"
    fi
    return
  fi

  nohup kubectl port-forward -n "$ns" "svc/$svc" "${local_port}:${remote_port}" \
    > "/tmp/pf-${svc}.log" 2>&1 &
  disown 2>/dev/null

  sleep 2
  if ss -tln 2>/dev/null | grep -q ":${local_port} "; then
    echo "  OK    $label — http://localhost:${local_port}"
  else
    echo "  FAIL  $label — see /tmp/pf-${svc}.log"
    tail -2 "/tmp/pf-${svc}.log" | sed 's/^/         /'
  fi
}

show_ssh_only() {
  local local_port=$1 label=$2
  if ss -tln 2>/dev/null | grep -q ":${local_port} "; then
    echo "  OK    $label — http://localhost:${local_port} (VM-local service, SSH tunnel)"
  else
    echo "  SKIP  $label — not listening on VM:${local_port} (start the service first)"
  fi
}

case "${1:-start}" in
  status)
    echo "=== Active kubectl port-forwards ==="
    local_pids=$(ss -tlnp 2>/dev/null \
      | grep -E ":(${ALL_PORTS_REGEX}) " \
      | grep -oP 'pid=\K[0-9]+' | sort -u)
    if [ -z "$local_pids" ]; then
      echo "(none)"
    else
      for pid in $local_pids; do
        cmd=$(ps -p "$pid" -o cmd= 2>/dev/null)
        etime=$(ps -p "$pid" -o etime= 2>/dev/null | tr -d ' ')
        if [ -n "$cmd" ] && echo "$cmd" | grep -q "port-forward"; then
          echo "  PID $pid  uptime $etime  $cmd"
        fi
      done
    fi
    echo ""
    echo "=== Listening ports ==="
    ss -tln 2>/dev/null | grep -E ":(${ALL_PORTS_REGEX}) " || echo "(none)"
    ;;

  stop)
    echo "Stopping all kubectl port-forwards..."
    pids=$(ss -tlnp 2>/dev/null \
      | grep -E ":(${ALL_PORTS_REGEX}) " \
      | grep -oP 'pid=\K[0-9]+' | sort -u)
    if [ -n "$pids" ]; then
      for pid in $pids; do
        cmd=$(ps -p "$pid" -o cmd= 2>/dev/null)
        if echo "$cmd" | grep -q "kubectl port-forward"; then
          kill "$pid" 2>/dev/null
        fi
      done
      sleep 1
      for pid in $pids; do
        if kill -0 "$pid" 2>/dev/null; then
          cmd=$(ps -p "$pid" -o cmd= 2>/dev/null)
          if echo "$cmd" | grep -q "kubectl port-forward"; then
            kill -9 "$pid" 2>/dev/null
          fi
        fi
      done
    fi
    pkill -f "kubectl port-forward" 2>/dev/null
    echo "Done. (SSH-only services like Jupyter Lab are NOT stopped — manage via systemctl.)"
    ;;

  restart)
    $0 stop
    sleep 1
    $0 start
    ;;

  start|"")
    echo "=== Starting port-forwards ==="
    forward_kubectl 9001 minio minio-console 9001 "MinIO Console"
    forward_kubectl 9000 minio minio 9000 "MinIO S3 API"
    forward_kubectl 8080 kubeflow ml-pipeline-ui 80 "Kubeflow Pipelines UI"
    forward_kubectl 5000 mlops mlflow 5000 "MLflow"
    forward_kubectl 3000 monitoring prometheus-grafana 80 "Grafana"
    forward_kubectl 9090 monitoring prometheus-kube-prometheus-prometheus 9090 "Prometheus"
    forward_kubectl 9093 monitoring prometheus-kube-prometheus-alertmanager 9093 "Alertmanager"
    forward_kubectl 8000 mlops fastapi 8000 "FastAPI"
    show_ssh_only 8889 "Jupyter Lab"
    echo ""
    echo "Useful: $0 status | $0 stop | $0 restart"
    ;;

  *)
    echo "Usage: $0 [start|stop|status|restart]"
    exit 1
    ;;
esac
